#!/system/bin/sh
#
#Control de WIPE
if [ -e /data/configsup.cf ];
then
echo "Existe en data, no ha habido Wipe";
else
echo " "
echo "Recuperacion de datos"
cp /system/backup/configsupcf /data/configsup.cf;
cp /system/backup/supconfig /data/sup.config;
cp /system/backup/bln /data/app/neldar.bln.control.free.apk;
cp /system/backup/voodoo /data/app/org.projectvoodoo.controlapp.apk;
sleep 2;
reboot;
fi;

sleep 1
# Lee en la configuracion 
#
if [ -e /data/configsup.cf ];
then
	# read it in
	. /data/configsup.cf;

	# read in the config
	lee_config;
	
	escribe_config;
fi;
#
# SetCPU Clocking
#
echo "$MAX_CPU" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
echo "$MIN_CPU" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;

#Para velocidad de escritura
#echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb

# Priorizador
#
if [ "$TURBO" = "YES" ];
then
echo "+++ Turbo 2 Activado"
#	/system/bin/prior &
	else
echo "***** Turbo 2 Desactivado";
fi;

# Super@tmel
#
if [ "$SUPERATMEL" = "YES" ];
then
echo "+++ Gracias a todos por elegir esta rom, espero que la disfruteis, y agradecimientos a todo el foro de Movilzona"
echo "***** Con SupSetup"
fi;

if [ -e /data/ctrsound ];
then
echo "Primera instalacion";
rm /data/ctrsound;
else
sleep 60
stop bootsound;
fi;
