#!/system/bin/sh
echo "Instalando Lenguaje para GPS si es necesario en 250 segundos"
sleep 250;
echo " Activando Instalador GPS"
if [ -e /data/lang/com.svox.langpack.installer.apk ];
	then
echo "***** Se instalara GPS";
busybox chown system.system /data/installlangpack;
busybox chmod 0755 /data/installlangpack;
	/data/installlangpack &
fi;
exit;

