#!/bin/sh
#
# Super-mega opticharger of doom
# Shrinks apks by running pngcrush on png images
#
# Point APKCERTS at the full path to a generated apkcerts.txt file, such as:
# /home/shade/dev/sources/android-cm-eclair/out/target/product/dream_sapphire/obj/PACKAGING/target_files_intermediates/cyanogen_dream_sapphire-target_files-eng.shade/META/apkcerts.txt
#
# cyanogen - shade@chemlab.org
# ChrisSoyars - me@ctso.me

OUT_TARGET_HOST=$(uname -a | grep Darwin)
if [ -z "$OUT_TARGET_HOST" ]
then
    OUT_TARGET_HOST=linux-x86
else
    OUT_TARGET_HOST=darwin-x86
fi

case "$TARGET_PRODUCT" in
	aosp_buzz) MDPI=1 ;;
	aosp_dream_sapphire) MDPI=1 ;;
	aosp_geeksphone) MDPI=1 ;;
	aosp_legend) MDPI=1 ;;
	aosp_hero) MDPI=1 ;;
	aosp_z71) MDPI=1 ;;
	*) MDPI=0
esac

# Discriminación de que dispositivos no tendran bateria circular
case "$TARGET_PRODUCT" in
	aosp_geeksphone) BATT=0 ;;
	aosp_passion) BATT=0 ;;
	aosp_crespo) BATT=0 ;;
	*) BATT=0
esac

# Discriminación de que dispositivos no tendran animacion especial
case "$TARGET_PRODUCT" in
	aosp_geeksphone) NOANIM=1 ;;
        aosp_hero) NOANIM=1 ;;
        aosp_dream_sapphire) NOANIM=1 ;;
        aosp_passion) NOANIM=1 ;;
	aosp_crespo) NOANIM=1 ;;
	*) NOANIM=0
esac

set -e
QUIET=1
QFLAG=-q
BASE=`pwd`
TMPDIR=/tmp/opticharge-$$
FRAME_IMG_MDPI=$ANDROID_BUILD_TOP/vendor/macsa/mods/frame_mdpi/*
FRAME_IMG_HDPI=$ANDROID_BUILD_TOP/vendor/macsa/mods/frame_hdpi/*
FRAME_IMG_MDPI_BATTERY=$ANDROID_BUILD_TOP/vendor/macsa/mods/frame_mdpi_battery/*
FRAME_IMG_HDPI_BATTERY=$ANDROID_BUILD_TOP/vendor/macsa/mods/frame_hdpi_battery/*
FRAME_ANIM=$ANDROID_BUILD_TOP/vendor/macsa/mods/anim/*
FRAME_IMG_MDPI_ONE=$ANDROID_BUILD_TOP/vendor/macsa/mods/frame_mdpi_one/*

if [ "$APKCERTS" = "" ];
then
    APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$LOGNAME/META/apkcerts.txt
    if [ ! -f "$APKCERTS" ];
    then
        echo "Set APKCERTS to the path to your apkcerts.txt file"
        exit 1;
    fi
fi

if [ ! -f "$APKCERTS" ];
then
    echo "Invalid path to apkcerts.txt, set APKCERTS to the correct path."
fi

if [ "`which pngcrush`" = "" ];
then
    echo "Please install pngcrush"
    exit 1;
fi

if [ "`which aapt`" = "" ];
then
    echo "Please ensure aapt is in your \$PATH"
    exit 1;
fi

if [ "`which zipalign`" = "" ];
then
    echo "Please ensure zipalign is in your \$PATH"
    exit 1;
fi

if [ -e "$1" ];
then
    NAME=`basename $1`;
    echo " Optimizing $NAME...";

    if [ "$2" != "" ];
    then
        CERT=build/target/product/security/$2.x509.pem
        KEY=build/target/product/security/$2.pk8
        if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
        then
            echo "$CERT does not exist!";
            exit 1;
        fi
    else
        APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
        [ $QUIET ] || echo "APKINFO: $APKINFO";
        if [ "$APKINFO" = "" ];
        then
            echo "No apk info for $NAME";
            exit 1;
        fi
        CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
        KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
        if [ "$CERT" = "" ];
        then
            echo "Unable to find certificate for $NAME"
            exit 1;
        fi
    fi

    [ $QUIET ] || echo "Certificate: $CERT";

    [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
    mkdir -p $TMPDIR/$NAME
    trap "rm -rf $TMPDIR; exit" INT TERM EXIT
    cd $TMPDIR/$NAME
    unzip -q $BASE/$1
    if [ "$MDPI" -eq 1 ]; then
	echo " Dispositivo MDPI"
	 cp -rf $FRAME_IMG_MDPI res/drawable-mdpi/
    if [ "$BATT" -eq 1 ]; then
	echo " Con bateria circular"
	 cp -rf $FRAME_IMG_MDPI_BATTERY res/drawable-mdpi/
    else
	echo " Con bateria original"
    fi
	if [ "$NOANIM" -eq 1 ]; then
	echo " Con animaciones normales"
		else
	echo " Con animaciones especiales"
	cp -rf $FRAME_ANIM res/anim/
	echo " "
fi
    else
	echo " Dispositivo HDPI"
	if [ "$NOANIM" -eq 1 ]; then
	echo " Con animaciones normales"
	 cp -rf $FRAME_IMG_HDPI res/drawable-hdpi/
	echo " "
		else
	echo " Con animaciones especiales"
	cp -r $FRAME_IMG_HDPI res/drawable-hdpi/
	cp -r $FRAME_ANIM res/anim/
	echo " "
fi
    if [ "$BATT" -eq 1 ]; then
	echo " Con bateria circular"
	 cp -rf $FRAME_IMG_HDPI_BATTERY res/drawable-hdpi/
    else
	echo " Con bateria original"
    fi
fi

case "$TARGET_PRODUCT" in
	aosp_geeksphone) cp -rf $FRAME_IMG_MDPI_ONE res/ ;;
	aosp_dream_sapphire) cp -rf $FRAME_IMG_MDPI_ONE res/ ;;
	*)
esac

    for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
    do
        [ $QUIET ] || echo "Crushing $x"
        pngcrush $QFLAG $x $x.crushed 1>/dev/null
        if [ -e "$x.crushed" ];
        then
            mv $x.crushed $x
        fi
    done
    cp $BASE/$1 $BASE/$1.old

    [ $QUIET ] || echo "Repacking apk.."
    aapt p -0 res/raw -0 res/raw-en -F $NAME .
    
    [ $QUIET ] || echo "Resigning with cert: `echo $CERT`"

    [ $QUIET ] || echo java -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
    java -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
    [ $QUIET ] || echo "Zipalign.."
    zipalign -f 4 signed_$NAME $BASE/$1
    if [ ! $QUIET ]; then
        ls -l $BASE/$1.old
        ls -l $BASE/$1
    fi
    rm $BASE/$1.old
else
    echo "Usage: $0 [apk file]"
fi

